# https://github.com/alacritty/alacritty/blob/master/alacritty.yml
# https://gitlab.com/evertiro/dotfiles/blob/master/.config/alacritty/alacritty.yml
# https://github.com/alexherbo2/alacritty-extended-keys/blob/master/keys.yml

env:
  # TERM: xterm-256color
  LANG: "en_US.UTF-8"

# Window Customization
window:
  dimensions:
    columns: 140
    lines: 38
  # padding:
  #   x: 25
  #   y: 25
  dynamic_padding: true
  decorations: full
  startup_mode: Fullscreen
  opacity: 1.0
  dynamic_title: true

scrolling:
  history: 10000
  multiplier: 3

# Font Customization
font:
  normal:
    family: Maple Mono NF
    # family: Liga InputMono Nerd Font Ligatures
    # family: OperatorMono Nerd Font
    # family: Iosevka Nerd Font
    # family: JetBrains Mono Nerd Font
    # family: Source Code Pro
    style: Regular

  bold:
    # family: OperatorMono Nerd Font
    family: Maple Mono NF
    style: Bold

  bold_italic:
    # family: OperatorMono Nerd Font
    family: Maple Mono NF
    style: Bold Italic

  italic:
    # family: Operator Mono Book
    # style: Book Italic
    family: Maple Mono NF
    style: Italic

  size: 10

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  debug:
    persistent_logging: false

draw_bold_text_with_bright_colors: false

# Color Settings (Gruvbox)
colors:
  # primary:
  #   background: "#0f0f0f"
  #   foreground: "#ebdbb2"

  # normal:
  #   black: "#282828"
  #   red: "#cc241d"
  #   green: "#98971a"
  #   yellow: "#d79921"
  #   blue: "#458588"
  #   magenta: "#b16286"
  #   cyan: "#689d6a"
  #   white: "#a89984"

  # bright:
  #   black: "#928374"
  #   red: "#fb4934"
  #   green: "#b8bb26"
  #   yellow: "#fabd2f"
  #   blue: "#83a598"
  #   magenta: "#d3869b"
  #   cyan: "#8ec07c"
  #   white: "#ebdbb2"

  # selection:
  #   text: "0xffffff"
  #   background: "0xdc3232"
  #   white: "0xffffff"
  primary:
    background: "#282a36"
    foreground: "#f8f8f2"
    bright_foreground: "#ffffff"
  cursor:
    text: CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
  search:
    matches:
      foreground: "#44475a"
      background: "#50fa7b"
    focused_match:
      foreground: "#44475a"
      background: "#ffb86c"
  hints:
    start:
      foreground: "#282a36"
      background: "#f1fa8c"
    end:
      foreground: "#f1fa8c"
      background: "#282a36"
  line_indicator:
    foreground: None
    background: None
  selection:
    text: CellForeground
    background: "#44475a"
  normal:
    black: "#21222c"
    red: "#ff5555"
    green: "#50fa7b"
    yellow: "#f1fa8c"
    blue: "#bd93f9"
    magenta: "#ff79c6"
    cyan: "#8be9fd"
    white: "#f8f8f2"
  bright:
    black: "#6272a4"
    red: "#ff6e6e"
    green: "#69ff94"
    yellow: "#ffffa5"
    blue: "#d6acff"
    magenta: "#ff92df"
    cyan: "#a4ffff"
    white: "#ffffff"

cursor:
  # Cursor style
  style:
    # Cursor shape
    #
    # Values for `shape`:
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
    shape: Beam

    # Cursor blinking state
    #
    # Values for `blinking`:
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    blinking: Off

  # Vi mode cursor style
  #
  # If the vi mode cursor style is `None` or not specified, it will fall back to
  # the style of the active value of the normal cursor.
  #
  # See `cursor.style` for available options.
  vi_mode_style:
    shape: Block
    blinking: off

  # Cursor blinking interval in milliseconds.
  blink_interval: 750

  # Time after which cursor stops blinking, in seconds.
  #
  # Specifying '0' will disable timeout for blinking.
  blink_timeout: 5

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  unfocused_hollow: true

  # Thickness of the cursor relative to the cell width as floating point number
  # from `0.0` to `1.0`.
  thickness: 0.15

key_bindings:
  - { key: T, mods: Alt, action: SpawnNewInstance }
  - { key: Return, mods: Alt, action: ToggleFullscreen }

  # Support for CSI u mode:

  # Control + <key> ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

  - { key: Return, mods: Control, chars: "\x1b[13;5u" }

  # Control + <letter> ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

  - { key: H, mods: Control, chars: "\x1b[104;5u" }
  - { key: I, mods: Control, chars: "\x1b[105;5u" }
  - { key: J, mods: Control, chars: "\x1b[106;5u" }
  - { key: M, mods: Control, chars: "\x1b[109;5u" }

  # Control + Shift + <letter> ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

  # Control + B ⇒ SearchBackward
  # Control + C ⇒ Copy
  # Control + F ⇒ SearchForward
  # Control + N ⇒ CreateNewWindow
  # Control + U ⇒ “EnterHintsMode”
  # Control + V ⇒ Paste

  - { key: A, mods: Control|Shift, chars: "\x1b[65;6u" }
  - { key: D, mods: Control|Shift, chars: "\x1b[68;6u" }
  - { key: E, mods: Control|Shift, chars: "\x1b[69;6u" }
  - { key: G, mods: Control|Shift, chars: "\x1b[71;6u" }
  - { key: H, mods: Control|Shift, chars: "\x1b[72;6u" }
  - { key: I, mods: Control|Shift, chars: "\x1b[73;6u" }
  - { key: J, mods: Control|Shift, chars: "\x1b[74;6u" }
  - { key: K, mods: Control|Shift, chars: "\x1b[75;6u" }
  - { key: L, mods: Control|Shift, chars: "\x1b[76;6u" }
  - { key: M, mods: Control|Shift, chars: "\x1b[77;6u" }
  - { key: O, mods: Control|Shift, chars: "\x1b[79;6u" }
  - { key: P, mods: Control|Shift, chars: "\x1b[80;6u" }
  - { key: Q, mods: Control|Shift, chars: "\x1b[81;6u" }
  - { key: R, mods: Control|Shift, chars: "\x1b[82;6u" }
  - { key: S, mods: Control|Shift, chars: "\x1b[83;6u" }
  - { key: T, mods: Control|Shift, chars: "\x1b[84;6u" }
  - { key: W, mods: Control|Shift, chars: "\x1b[87;6u" }
  - { key: X, mods: Control|Shift, chars: "\x1b[88;6u" }
  - { key: Y, mods: Control|Shift, chars: "\x1b[89;6u" }
  - { key: Z, mods: Control|Shift, chars: "\x1b[90;6u" }

  # Control + <number> ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

  # Control + 0 ⇒ ResetFontSize

  - { key: Key1, mods: Control, chars: "\x1b[49;5u" }
  - { key: Key2, mods: Control, chars: "\x1b[50;5u" }
  - { key: Key3, mods: Control, chars: "\x1b[51;5u" }
  - { key: Key4, mods: Control, chars: "\x1b[52;5u" }
  - { key: Key5, mods: Control, chars: "\x1b[53;5u" }
  - { key: Key6, mods: Control, chars: "\x1b[54;5u" }
  - { key: Key7, mods: Control, chars: "\x1b[55;5u" }
  - { key: Key8, mods: Control, chars: "\x1b[56;5u" }
  - { key: Key9, mods: Control, chars: "\x1b[57;5u" }

  # Control + Shift + <number> ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

  - { key: Key0, mods: Control|Shift, chars: "\x1b[48;6u" }
  - { key: Key1, mods: Control|Shift, chars: "\x1b[49;6u" }
  - { key: Key2, mods: Control|Shift, chars: "\x1b[50;6u" }
  - { key: Key3, mods: Control|Shift, chars: "\x1b[51;6u" }
  - { key: Key4, mods: Control|Shift, chars: "\x1b[52;6u" }
  - { key: Key5, mods: Control|Shift, chars: "\x1b[53;6u" }
  - { key: Key6, mods: Control|Shift, chars: "\x1b[54;6u" }
  - { key: Key7, mods: Control|Shift, chars: "\x1b[55;6u" }
  - { key: Key8, mods: Control|Shift, chars: "\x1b[56;6u" }
  - { key: Key9, mods: Control|Shift, chars: "\x1b[57;6u" }

  # Support Alt keys for macOS:

  # Alt + <letter> ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

  - { key: A, mods: Alt, chars: "\x1ba" }
  - { key: B, mods: Alt, chars: "\x1bb" }
  - { key: C, mods: Alt, chars: "\x1bc" }
  - { key: D, mods: Alt, chars: "\x1bd" }
  - { key: E, mods: Alt, chars: "\x1be" }
  - { key: F, mods: Alt, chars: "\x1bf" }
  - { key: G, mods: Alt, chars: "\x1bg" }
  - { key: H, mods: Alt, chars: "\x1bh" }
  - { key: I, mods: Alt, chars: "\x1bi" }
  - { key: J, mods: Alt, chars: "\x1bj" }
  - { key: K, mods: Alt, chars: "\x1bk" }
  - { key: L, mods: Alt, chars: "\x1bl" }
  - { key: M, mods: Alt, chars: "\x1bm" }
  - { key: N, mods: Alt, chars: "\x1bn" }
  - { key: O, mods: Alt, chars: "\x1bo" }
  - { key: P, mods: Alt, chars: "\x1bp" }
  - { key: Q, mods: Alt, chars: "\x1bq" }
  - { key: R, mods: Alt, chars: "\x1br" }
  - { key: S, mods: Alt, chars: "\x1bs" }
  - { key: T, mods: Alt, chars: "\x1bt" }
  - { key: U, mods: Alt, chars: "\x1bu" }
  - { key: V, mods: Alt, chars: "\x1bv" }
  - { key: W, mods: Alt, chars: "\x1bw" }
  - { key: X, mods: Alt, chars: "\x1bx" }
  - { key: Y, mods: Alt, chars: "\x1by" }
  - { key: Z, mods: Alt, chars: "\x1bz" }

  # Alt + Shift + <letter> ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

  - { key: A, mods: Alt|Shift, chars: "\x1bA" }
  - { key: B, mods: Alt|Shift, chars: "\x1bB" }
  - { key: C, mods: Alt|Shift, chars: "\x1bC" }
  - { key: D, mods: Alt|Shift, chars: "\x1bD" }
  - { key: E, mods: Alt|Shift, chars: "\x1bE" }
  - { key: F, mods: Alt|Shift, chars: "\x1bF" }
  - { key: G, mods: Alt|Shift, chars: "\x1bG" }
  - { key: H, mods: Alt|Shift, chars: "\x1bH" }
  - { key: I, mods: Alt|Shift, chars: "\x1bI" }
  - { key: J, mods: Alt|Shift, chars: "\x1bJ" }
  - { key: K, mods: Alt|Shift, chars: "\x1bK" }
  - { key: L, mods: Alt|Shift, chars: "\x1bL" }
  - { key: M, mods: Alt|Shift, chars: "\x1bM" }
  - { key: N, mods: Alt|Shift, chars: "\x1bN" }
  - { key: O, mods: Alt|Shift, chars: "\x1bO" }
  - { key: P, mods: Alt|Shift, chars: "\x1bP" }
  - { key: Q, mods: Alt|Shift, chars: "\x1bQ" }
  - { key: R, mods: Alt|Shift, chars: "\x1bR" }
  - { key: S, mods: Alt|Shift, chars: "\x1bS" }
  - { key: T, mods: Alt|Shift, chars: "\x1bT" }
  - { key: U, mods: Alt|Shift, chars: "\x1bU" }
  - { key: V, mods: Alt|Shift, chars: "\x1bV" }
  - { key: W, mods: Alt|Shift, chars: "\x1bW" }
  - { key: X, mods: Alt|Shift, chars: "\x1bX" }
  - { key: Y, mods: Alt|Shift, chars: "\x1bY" }
  - { key: Z, mods: Alt|Shift, chars: "\x1bZ" }

  # Alt + <number> ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

  - { key: Key0, mods: Alt, chars: "\x1b0" }
  - { key: Key1, mods: Alt, chars: "\x1b1" }
  - { key: Key2, mods: Alt, chars: "\x1b2" }
  - { key: Key3, mods: Alt, chars: "\x1b3" }
  - { key: Key4, mods: Alt, chars: "\x1b4" }
  - { key: Key5, mods: Alt, chars: "\x1b5" }
  - { key: Key6, mods: Alt, chars: "\x1b6" }
  - { key: Key7, mods: Alt, chars: "\x1b7" }
  - { key: Key8, mods: Alt, chars: "\x1b8" }
  - { key: Key9, mods: Alt, chars: "\x1b9" }

  # Alt + <character> ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

  - { key: Grave, mods: Alt, chars: "\x1b`" }
  - { key: Minus, mods: Alt, chars: "\x1b-" }
  - { key: Equals, mods: Alt, chars: "\x1b=" }
  - { key: LBracket, mods: Alt, chars: "\x1b[" }
  - { key: RBracket, mods: Alt, chars: "\x1b]" }
  - { key: Backslash, mods: Alt, chars: "\x1b\\" }
  - { key: Semicolon, mods: Alt, chars: "\x1b;" }
  - { key: Apostrophe, mods: Alt, chars: "\x1b'" }
  - { key: Comma, mods: Alt, chars: "\x1b," }
  - { key: Period, mods: Alt, chars: "\x1b." }
  - { key: Slash, mods: Alt, chars: "\x1b/" }

  # Alt + Shift + <character> ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

  - { key: Grave, mods: Alt|Shift, chars: "\x1b~" }
  - { key: Key1, mods: Alt|Shift, chars: "\x1b!" }
  - { key: Key2, mods: Alt|Shift, chars: "\x1b@" }
  - { key: Key3, mods: Alt|Shift, chars: "\x1b#" }
  - { key: Key4, mods: Alt|Shift, chars: "\x1b$" }
  - { key: Key5, mods: Alt|Shift, chars: "\x1b%" }
  - { key: Key6, mods: Alt|Shift, chars: "\x1b^" }
  - { key: Key7, mods: Alt|Shift, chars: "\x1b&" }
  - { key: Key8, mods: Alt|Shift, chars: "\x1b*" }
  - { key: Key9, mods: Alt|Shift, chars: "\x1b(" }
  - { key: Key0, mods: Alt|Shift, chars: "\x1b)" }
  - { key: Minus, mods: Alt|Shift, chars: "\x1b_" }
  - { key: Equals, mods: Alt|Shift, chars: "\x1b+" }
  - { key: LBracket, mods: Alt|Shift, chars: "\x1b{" }
  - { key: RBracket, mods: Alt|Shift, chars: "\x1b}" }
  - { key: Backslash, mods: Alt|Shift, chars: "\x1b|" }
  - { key: Semicolon, mods: Alt|Shift, chars: "\x1b:" }
  - { key: Apostrophe, mods: Alt|Shift, chars: "\x1b\"" }
  - { key: Comma, mods: Alt|Shift, chars: "\x1b<" }
  - { key: Period, mods: Alt|Shift, chars: "\x1b>" }
  - { key: Slash, mods: Alt|Shift, chars: "\x1b?" }

  - { key: F1, mods: Shift, chars: "\x1b[1;2P" }
  - { key: F2, mods: Shift, chars: "\x1b[1;2Q" }
  - { key: F3, mods: Shift, chars: "\x1b[1;2R" }
  - { key: F4, mods: Shift, chars: "\x1b[1;2S" }
  - { key: F5, mods: Shift, chars: "\x1b[15;2~" }
  - { key: F6, mods: Shift, chars: "\x1b[17;2~" }
  - { key: F7, mods: Shift, chars: "\x1b[18;2~" }
  - { key: F8, mods: Shift, chars: "\x1b[19;2~" }
  - { key: F9, mods: Shift, chars: "\x1b[20;2~" }
  - { key: F10, mods: Shift, chars: "\x1b[21;2~" }
  - { key: F11, mods: Shift, chars: "\x1b[23;2~" }
  - { key: F12, mods: Shift, chars: "\x1b[24;2~" }
  - { key: F1, mods: Control, chars: "\x1b[1;5P" }
  - { key: F2, mods: Control, chars: "\x1b[1;5Q" }
  - { key: F3, mods: Control, chars: "\x1b[1;5R" }
  - { key: F4, mods: Control, chars: "\x1b[1;5S" }
  - { key: F5, mods: Control, chars: "\x1b[15;5~" }
  - { key: F6, mods: Control, chars: "\x1b[17;5~" }
  - { key: F7, mods: Control, chars: "\x1b[18;5~" }
  - { key: F8, mods: Control, chars: "\x1b[19;5~" }
  - { key: F9, mods: Control, chars: "\x1b[20;5~" }
  - { key: F10, mods: Control, chars: "\x1b[21;5~" }
  - { key: F11, mods: Control, chars: "\x1b[23;5~" }
  - { key: F12, mods: Control, chars: "\x1b[24;5~" }
  - { key: F1, mods: Alt, chars: "\x1b[1;6P" }
  - { key: F2, mods: Alt, chars: "\x1b[1;6Q" }
  - { key: F3, mods: Alt, chars: "\x1b[1;6R" }
  - { key: F4, mods: Alt, chars: "\x1b[1;6S" }
  - { key: F5, mods: Alt, chars: "\x1b[15;6~" }
  - { key: F6, mods: Alt, chars: "\x1b[17;6~" }
  - { key: F7, mods: Alt, chars: "\x1b[18;6~" }
  - { key: F8, mods: Alt, chars: "\x1b[19;6~" }
  - { key: F9, mods: Alt, chars: "\x1b[20;6~" }
  - { key: F10, mods: Alt, chars: "\x1b[21;6~" }
  - { key: F11, mods: Alt, chars: "\x1b[23;6~" }
  - { key: F12, mods: Alt, chars: "\x1b[24;6~" }
  - { key: F1, mods: Super, chars: "\x1b[1;3P" }
  - { key: F2, mods: Super, chars: "\x1b[1;3Q" }
  - { key: F3, mods: Super, chars: "\x1b[1;3R" }
  - { key: F4, mods: Super, chars: "\x1b[1;3S" }
  - { key: F5, mods: Super, chars: "\x1b[15;3~" }
  - { key: F6, mods: Super, chars: "\x1b[17;3~" }
  - { key: F7, mods: Super, chars: "\x1b[18;3~" }
  - { key: F8, mods: Super, chars: "\x1b[19;3~" }
  - { key: F9, mods: Super, chars: "\x1b[20;3~" }
  - { key: F10, mods: Super, chars: "\x1b[21;3~" }
  - { key: F11, mods: Super, chars: "\x1b[23;3~" }
  - { key: F12, mods: Super, chars: "\x1b[24;3~" }
  # import:
  # - /home/alpha2phi/.config/alacritty/dracula.yml
