# https://github.com/alacritty/alacritty/blob/master/alacritty.yml
# https://gitlab.com/evertiro/dotfiles/blob/master/.config/alacritty/alacritty.yml
# https://github.com/alexherbo2/alacritty-extended-keys/blob/master/keys.yml

env:
  TERM: xterm-256color
  LANG: "en_US.UTF-8"

# Window Customization
window:
  dimensions:
    columns: 140
    lines: 38
  # padding:
  #   x: 25
  #   y: 25
  dynamic_padding: true
  decorations: none
  startup_mode: Fullscreen

scrolling:
  history: 10000
  multiplier: 3

window.opacity: 0.8
window.dynamic_title: true

# Font Customization
font:
  normal:
    family: FiraCode Nerd Font
    # family: Liga InputMono Nerd Font Ligatures
    # family: OperatorMono Nerd Font
    # family: Iosevka Nerd Font
    # family: JetBrains Mono Nerd Font
    # family: Source Code Pro
    style: Retina

  bold:
    family: OperatorMono Nerd Font
    style: Bold

  bold_italic:
    family: OperatorMono Nerd Font
    style: Bold Italic

  italic:
    family: Operator Mono Book
    style: Book Italic

  size: 9.5

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: false

  debug:
    persistent_logging: false

draw_bold_text_with_bright_colors: true

# Color Settings (Gruvbox)
colors:
  # primary:
  #   background: "#0f0f0f"
  #   foreground: "#ebdbb2"

  # normal:
  #   black: "#282828"
  #   red: "#cc241d"
  #   green: "#98971a"
  #   yellow: "#d79921"
  #   blue: "#458588"
  #   magenta: "#b16286"
  #   cyan: "#689d6a"
  #   white: "#a89984"

  # bright:
  #   black: "#928374"
  #   red: "#fb4934"
  #   green: "#b8bb26"
  #   yellow: "#fabd2f"
  #   blue: "#83a598"
  #   magenta: "#d3869b"
  #   cyan: "#8ec07c"
  #   white: "#ebdbb2"

  # selection:
  #   text: "0xffffff"
  #   background: "0xdc3232"
  #   white: "0xffffff"
  primary:
    background: "#282a36"
    foreground: "#f8f8f2"
    bright_foreground: "#ffffff"
  cursor:
    text: CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
  search:
    matches:
      foreground: "#44475a"
      background: "#50fa7b"
    focused_match:
      foreground: "#44475a"
      background: "#ffb86c"
    bar:
      background: "#282a36"
      foreground: "#f8f8f2"
  hints:
    start:
      foreground: "#282a36"
      background: "#f1fa8c"
    end:
      foreground: "#f1fa8c"
      background: "#282a36"
  line_indicator:
    foreground: None
    background: None
  selection:
    text: CellForeground
    background: "#44475a"
  normal:
    black: "#21222c"
    red: "#ff5555"
    green: "#50fa7b"
    yellow: "#f1fa8c"
    blue: "#bd93f9"
    magenta: "#ff79c6"
    cyan: "#8be9fd"
    white: "#f8f8f2"
  bright:
    black: "#6272a4"
    red: "#ff6e6e"
    green: "#69ff94"
    yellow: "#ffffa5"
    blue: "#d6acff"
    magenta: "#ff92df"
    cyan: "#a4ffff"
    white: "#ffffff"

cursor:
  style: Block
  unfocused_hollow: true

key_bindings:
  - { key: T, mods: Alt, action: SpawnNewInstance }
  - { key: A, mods: Alt, chars: "\x1ba" }
  - { key: J, mods: Alt, chars: "\x1bj" }
  - { key: K, mods: Alt, chars: "\x1bk" }
  - { key: H, mods: Alt, chars: "\x1bh" }
  - { key: L, mods: Alt, chars: "\x1bl" }
  - { key: X, mods: Alt, chars: "\x1bx" }
  - { key: V, mods: Alt, chars: "\x1bv" }
  - { key: S, mods: Alt, chars: "\x1bs" }
  - { key: Z, mods: Alt, chars: "\x1bz" }
  - { key: Return, mods: Alt, action: ToggleFullscreen }
# import:
# - /home/alpha2phi/.config/alacritty/dracula.yml
