# Window Customization
window:
  dimensions:
    columns: 140
    lines: 38
  padding:
    x: 25
    y: 25
  decorations: none
scrolling:
  history: 10000
  multiplier: 3
background_opacity: 0.8
window.dynamic_title: true

# Font Customization
font:
  # normal:
  #   family: Fira Code
  #   style: Regular
  # bold:
  #   family: Fira Code
  #   style: Bold
  # italic:
  #   family: Fira Code
  #   style: Italic
  size: 14
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  use_thin_strokes: false
  debug:
    persistent_logging: false
draw_bold_text_with_bright_colors: true

# Color Settings (Gruvbox)
colors:
  primary:
    background: '#0f0f0f'
    foreground: '#ebdbb2'

  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'

  selection:
    text: '0xffffff'
    background: '0xdc3232'
    white:   '0xffffff'
cursor:
  style: Block
  unfocused_hollow: true

key_bindings:
  - { key: T, mods: Control, action: SpawnNewInstance }
  - { key: A, mods: Alt,     chars: "\x1ba" }
  - { key: J, mods: Alt,     chars: "\x1bj" }
  - { key: K, mods: Alt,     chars: "\x1bk" }
  - { key: H, mods: Alt,     chars: "\x1bh" }
  - { key: L, mods: Alt,     chars: "\x1bl" }
  - { key: X, mods: Alt,     chars: "\x1bx" }
  - { key: V, mods: Alt,     chars: "\x1bv" }
  - { key: S, mods: Alt,     chars: "\x1bs" }
  - { key: Z, mods: Alt,     chars: "\x1bz" }
