[[snippets]]
  description = "docker prune"
  command = "docker system prune -a"
  output = ""

[[snippets]]
  description = "process subst 1"
  command = "vim <(ls -la)"
  output = ""

[[snippets]]
  description = "process subst 2"
  command = "ls -la | vim -"
  output = ""

[[snippets]]
  description = "npm list"
  command = "npm list --global"
  output = ""

[[snippets]]
  description = "pip uninstall"
  command = "pip list | grep robot | awk '{print $1}' | xargs pip uninstall -y"
  output = ""

[[snippets]]
  description = "ls sort size"
  command = "ls -lSr"
  output = ""

[[snippets]]
  description = "docker rm containers"
  command = "docker rm -f $(docker ps -a -q)"
  output = ""

[[snippets]]
  description = "docker rm images"
  command = "docker rmi $(docker images -a -q)"
  output = ""

[[snippets]]
  description = "bare zsh"
  command = "zsh -df"
  output = ""
